spring.application.name=taskmanager
# Diese Werte werden in Render als Environment Variables gesetzt.
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
# Hibernate legt die Tabelle für die Task-Entity automatisch an oder aktualisiert sie.
spring.jpa.hibernate.ddl-auto=update
